spring.application.name=github-info
server.port=8080

# db connection
spring.datasource.url=jdbc:postgresql://postgresql:5432/github-info
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=user
spring.datasource.password=user
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.liquibase.enabled=true
spring.liquibase.change-log=liquibase/liquibase-changelog.yaml

# feign
spring.cloud.openfeign.circuitbreaker.enabled=true
spring.cloud.openfeign.client.config.githubClient.url=https://api.github.com/